"""Every value a past release shipped in config/mcp-registry.toml.example
that the current one no longer holds, keyed the way template_sync's
migrations are: (table path, key) for a table's own key, or (table path,
"<key>.<field>") for a string field of a property's inline table.

A cousin's registry is copied at spawn and synced additively after that,
so a value the framework later changed stays in the cousin's copy unless
the sync knows that exact text was the framework's own. This table is
that knowledge, read from git history rather than kept by hand: a
schema that grew while a home's `options` did not is how `remember`
lost `scope` on the argv path (3.36.1).

Regenerate after a registry change: `python -m cousin_lib.registry_history
--write` from a full clone. tests/test_registry_history.py fails while a
past value is missing here.
"""
import subprocess
import sys
import tomllib
from pathlib import Path

REGISTRY = "config/mcp-registry.toml.example"
BEGIN = "# --- generated by `python -m cousin_lib.registry_history --write` ---\n"
END = "# --- end generated ---\n"


def entries(registry, path=""):
    """(table path, spec, value) for every migratable value: a table's
    plain keys (an `options` or `argv` value whole), a property's inline
    table whole, and each string field of it."""
    for key, value in registry.items():
        here = "%s.%s" % (path, key) if path else key
        if isinstance(value, dict) and path.endswith(".properties"):
            # the whole table first (an enum, a type, an items change),
            # then each string field for a cousin who edited another one
            yield path, key, value
            for field, text in value.items():
                if isinstance(text, str):
                    yield path, "%s.%s" % (key, field), text
        elif isinstance(value, dict) and key != "options":
            yield from entries(value, here)
        else:
            yield path, key, value


def from_git(checkout):
    """{(table, spec): [old values, newest first]} from every commit that
    touched the shipped registry, against the checkout's own copy."""
    checkout = Path(checkout)

    def git(*args):
        return subprocess.run(["git", "-C", str(checkout), *args], capture_output=True,
                              text=True, check=True).stdout

    current = {(t, s): v for t, s, v in
               entries(tomllib.loads((checkout / REGISTRY).read_text()))}
    out = {}
    for rev in git("log", "--format=%H", "--", REGISTRY).split():
        try:
            old = tomllib.loads(git("show", "%s:%s" % (rev, REGISTRY)))
        except (subprocess.CalledProcessError, tomllib.TOMLDecodeError):
            continue
        for table, spec, value in entries(old):
            key = (table, spec)
            if key in current and value != current[key] and value not in out.get(key, []):
                out.setdefault(key, []).append(value)
    return out


def render(history):
    lines = ["SHIPPED_BEFORE = {"]
    for key in sorted(history):
        lines.append("    %r: (" % (key,))
        lines.extend("        %r," % (value,) for value in history[key])
        lines.append("    ),")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv=None):
    """Print the table from git history; --write puts it in this file."""
    argv = sys.argv[1:] if argv is None else argv
    here = Path(__file__)
    table = render(from_git(here.resolve().parents[1]))
    if "--write" not in argv:
        sys.stdout.write(table)
        return 0
    text = here.read_text()
    head, _, rest = text.partition(BEGIN)
    _, _, tail = rest.partition(END)
    here.write_text(head + BEGIN + table + END + tail)
    return 0


# --- generated by `python -m cousin_lib.registry_history --write` ---
SHIPPED_BEFORE = {
    ('tools.job', 'description'): (
        'Track sub-agents and background work: start, done, fail, list, show.',
    ),
    ('tools.job.commands.run', 'argv'): (
        ['start', 'shell', '{title}', '--json', '--', '{argv}'],
    ),
    ('tools.job.commands.run', 'options'): (
        {'desc': '--desc', 'log': '--home-log'},
        {'desc': '--desc', 'log': '--log'},
    ),
    ('tools.job.commands.start', 'argv'): (
        ['start', '{kind}', '{title}'],
    ),
    ('tools.job.properties', 'desc'): (
        {'type': 'string', 'description': 'context for the job (start)'},
    ),
    ('tools.job.properties', 'desc.description'): (
        'context for the job (start)',
    ),
    ('tools.job.properties', 'kind'): (
        {'type': 'string', 'enum': ['subagent', 'build', 'other'], 'description': '(start) not shell: start takes no command, so a shell row would never close. For long shell work use a Bash call with run_in_background (tracked automatically by the job hooks), or run `cousin-job start shell TITLE -- CMD` from a shell, which launches CMD and closes the row with its exit code'},
        {'type': 'string', 'enum': ['subagent', 'shell', 'build', 'other'], 'description': '(start)'},
    ),
    ('tools.job.properties', 'kind.description'): (
        '(start) not shell: start takes no command, so a shell row would never close. For long shell work use a Bash call with run_in_background (tracked automatically by the job hooks), or run `cousin-job start shell TITLE -- CMD` from a shell, which launches CMD and closes the row with its exit code',
        '(start)',
    ),
    ('tools.job.properties', 'log'): (
        {'type': 'string', 'optional': True, 'description': "log file, relative to your home; default: the job's own log under data/job-logs (run)"},
    ),
    ('tools.job.properties', 'log.description'): (
        "log file, relative to your home; default: the job's own log under data/job-logs (run)",
    ),
    ('tools.job.properties', 'title'): (
        {'type': 'string', 'description': '(start)'},
    ),
    ('tools.job.properties', 'title.description'): (
        '(start)',
    ),
    ('tools.memory', 'description'): (
        "Durable memory: search what you wrote, log a decision with its reasoning, remember a fact with its truth level (operator = the operator said it, needs cite), mark a topic obsolete when something superseded it (why required; it leaves the distilled views, raw keeps the history), recall what you wrote (the best matches for a keyword, or the newest entries), walk an entry's provenance (why: what it was built from and what was built on it), checkpoint your current activity.",
        'Durable memory: search what you wrote, log a decision with its reasoning, remember a fact with its truth level (operator = the operator said it, needs cite), mark a topic obsolete when something superseded it (why required; it leaves the distilled views, raw keeps the history), recall past decisions, checkpoint your current activity.',
        'Durable memory: search what you wrote, log a decision with its reasoning, remember a fact with its truth level (operator = the operator said it, needs cite), recall past decisions, checkpoint your current activity.',
        'Durable memory: search what you wrote, log a decision with its reasoning, recall past decisions, checkpoint your current activity.',
    ),
    ('tools.memory.commands.decide', 'options'): (
        {'level': '--level', 'cite': '--cite'},
    ),
    ('tools.memory.commands.obsolete', 'options'): (
        {'why': '--why', 'force': '--force'},
    ),
    ('tools.memory.commands.remember', 'options'): (
        {'level': '--level', 'cite': '--cite', 'derived_from': '--derived-from'},
        {'level': '--level', 'cite': '--cite'},
    ),
    ('tools.memory.commands.why', 'options'): (
        {'json': '--json'},
    ),
    ('tools.memory.properties', 'depth'): (
        {'type': 'integer', 'optional': True, 'description': 'hops to walk each way; default the whole chain (why)'},
    ),
    ('tools.memory.properties', 'depth.description'): (
        'hops to walk each way; default the whole chain (why)',
    ),
    ('tools.memory.properties', 'derived_from'): (
        {'type': 'array', 'items': 'string', 'optional': True, 'description': 'entry ids this was built from, one hop (decide, remember); `why` walks it'},
    ),
    ('tools.memory.properties', 'derived_from.description'): (
        'entry ids this was built from, one hop (decide, remember); `why` walks it',
    ),
    ('tools.memory.properties', 'keyword'): (
        {'type': 'string', 'optional': True, 'description': 'filter (recall)'},
    ),
    ('tools.memory.properties', 'keyword.description'): (
        'filter (recall)',
    ),
    ('tools.memory.properties', 'topic'): (
        {'type': 'string', 'description': 'decision topic (decide)'},
    ),
    ('tools.memory.properties', 'topic.description'): (
        'decision topic (decide)',
    ),
    ('tools.send.commands.operator', 'options'): (
        {'to': '--user', 'image': '--image'},
        {'to': '--user'},
    ),
}
# --- end generated ---


if __name__ == "__main__":
    sys.exit(main())
