"""The tool-surface manifest.

One line per console script (its name and the first line of its
`--help`) written to <root>/data/tool-surface.md, a list a cousin can
read instead of re-discovering its CLIs. The script list is derived,
never typed: from the installed package's entry points when it is
installed, else from pyproject.toml in the checkout. A CLI cannot ship without a line
here, and a line cannot name a CLI that does not exist.
"""
import argparse
import os
import subprocess
import sys
import tomllib
from datetime import datetime, timezone
from pathlib import Path

from cousin_lib.config import FrameworkConfig, MissingConfigError

DISTRIBUTION = "cousins-framework"
MANIFEST_RELPATH = Path("data") / "tool-surface.md"
NO_HELP = "(no --help available)"
HELP_TIMEOUT_S = 20


def scripts_from_pyproject(path):
    """[(name, "module:func"), ...] from a pyproject's
    [project.scripts]; an unreadable file is an empty list."""
    try:
        data = tomllib.loads(Path(path).read_text())
    except (OSError, tomllib.TOMLDecodeError):
        return []
    scripts = data.get("project", {}).get("scripts", {})
    return [(name, target) for name, target in scripts.items()]


def scripts_from_entry_points():
    """[(name, "module:func"), ...] from the installed distribution;
    None when the package is not installed."""
    import importlib.metadata as md
    try:
        dist = md.distribution(DISTRIBUTION)
    except md.PackageNotFoundError:
        return None
    rows = [(ep.name, ep.value) for ep in dist.entry_points
            if ep.group == "console_scripts"]
    return rows or None


def console_scripts():
    """The checkout's pyproject first (an editable install's recorded
    entry points go stale the moment a script is added; the file beside
    the module is the source of truth), else the installed entry points."""
    pyproject = Path(__file__).resolve().parents[1] / "pyproject.toml"
    if pyproject.is_file():
        rows = scripts_from_pyproject(pyproject)
        if rows:
            return rows
    return scripts_from_entry_points()


def _first_usage(text):
    """The first non-empty line of --help, with argparse's indented
    continuation lines folded in, as one line."""
    lines = text.splitlines()
    while lines and not lines[0].strip():
        lines.pop(0)
    if not lines:
        return ""
    parts = [lines[0].strip()]
    for line in lines[1:]:
        if line[:1].isspace() and line.strip():
            parts.append(line.strip())
        else:
            break
    return " ".join(parts)


def describe(name, target, bin_dir=None):
    """First line of `<script> --help`. With bin_dir the installed
    wrapper runs; otherwise the entry point runs through this
    interpreter, so an uninstalled checkout still describes itself."""
    if bin_dir:
        cmd = [str(Path(bin_dir) / name), "--help"]
    else:
        module, _, func = target.partition(":")
        code = ("import sys; from %s import %s as m;"
                " sys.exit(m(['--help']))" % (module, func))
        cmd = [sys.executable, "-c", code]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True,
                              timeout=HELP_TIMEOUT_S,
                              env={**os.environ, "COLUMNS": "200"})
    except (OSError, subprocess.TimeoutExpired):
        return NO_HELP
    if proc.returncode != 0 and not proc.stdout.strip():
        return NO_HELP
    return _first_usage(proc.stdout) or _first_usage(proc.stderr) \
        or NO_HELP


def build_manifest(scripts, *, describe=describe, bin_dir=None):
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    lines = [
        "# Tool Surface",
        "",
        "Generated by cousin-tool-surface from each script's --help;"
        " do not edit by hand. Generated: %s" % stamp,
        "",
    ]
    for name, target in scripts:
        lines.append("- `%s` - %s" % (name, describe(name, target,
                                                    bin_dir=bin_dir)))
    lines += ["", "Run `<tool> --help` for the full surface;"
              " `<tool> <subcommand> --help` for one subcommand.", ""]
    return "\n".join(lines)


def write_manifest(root, text):
    """Staged then renamed: a reader never sees a half-written file."""
    path = Path(root) / MANIFEST_RELPATH
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(text)
    os.replace(tmp, path)
    return path


def tool_surface_main(argv=None):
    """cousin-tool-surface [--root R] [--bin DIR]. Exit 0 written,
    1 no scripts found, 2 usage."""
    parser = argparse.ArgumentParser(
        prog="cousin-tool-surface",
        description="write <root>/data/tool-surface.md, one line per"
                    " console script, from each script's --help")
    parser.add_argument("--root", default=None,
                        help="framework root (else FRAMEWORK_ROOT)")
    parser.add_argument("--bin", default=None,
                        help="directory holding the installed cousin-*"
                             " wrappers; default runs each entry point"
                             " through this interpreter")
    args = parser.parse_args(argv)
    try:
        root = FrameworkConfig.resolve(args.root, cwd_fallback=True).root
    except MissingConfigError as err:
        print("cousin-tool-surface: %s" % err, file=sys.stderr)
        return 2
    scripts = console_scripts()
    if not scripts:
        print("cousin-tool-surface: no console scripts found (package"
              " not installed and no pyproject.toml beside the module)",
              file=sys.stderr)
        return 1
    # describe is looked up at call time, not bound at definition, so a
    # test (or a wrapper) can substitute it through the module.
    path = write_manifest(root, build_manifest(scripts, describe=describe,
                                               bin_dir=args.bin))
    print("wrote %s (%d tools)" % (path, len(scripts)))
    return 0
